# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('wifi-he', ['wifi', 'network', 'propagation', 'energy', 'spectrum', 'antenna', 'mobility'])
    module.source = [
        'model/constant-obss-pd-algorithm.cc',
        'model/obss-pd-algorithm.cc',
        'helper/wifi-he-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('wifi-he')
    module_test.source = [
        'test/wifi-he-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'wifi-he'
    headers.source = [
        'model/constant-obss-pd-algorithm.h',
        'model/obss-pd-algorithm.h',
        'helper/wifi-he-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

